### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Chamod Neluhena",
  "email": "cneluhena@gmail.com",
  "address": "Negombo Kurana",
  "phone": "0713805613",
  "dateOfBirth": "2000-08-19",
  "registeredDate": "2025-11-24"

}


###